all:
  children:
    web:
      hosts:
        srv_web:
          ansible_host: 192.168.56.111
          ansible_user: vagrant
          ansible_ssh_private_key_file: /home/aure/.ssh/insecure_private_key

    db:
      hosts:
        srv_db:
          ansible_host: 192.168.56.112
          ansible_user: vagrant
          ansible_ssh_private_key_file: /home/aure/.ssh/insecure_private_key
